previews:
  generation: off

services:
  - type: web
    name: flowops-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    autoDeployTrigger: commit
    healthCheckPath: /actuator/health
    envVars:
      - key: APP_ALLOWED_ORIGINS
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: JASYPT_ENCRYPTOR_PASSWORD
        sync: false
      - key: JASYPT_ENCRYPTOR_ALGORITHM
        value: "PBEWITHHMACSHA512ANDAES_256"
      - key: JASYPT_ENCRYPTOR_KEY_OBTENTION_ITERATIONS
        value: "1000"
      - key: JASYPT_ENCRYPTOR_SALT_GENERATOR_CLASSNAME
        value: "org.jasypt.salt.RandomSaltGenerator"
      - key: JASYPT_ENCRYPTOR_IV_GENERATOR_CLASSNAME
        value: "org.jasypt.iv.RandomIvGenerator"
      - key: JASYPT_ENCRYPTOR_STRING_OUTPUT_TYPE
        value: "base64"
      - key: DB_POOL_MAX_SIZE
        value: "3"
      - key: GITHUB_MOCK_ENABLED
        value: "false"
      - key: GITHUB_TOKEN
        value: ${GITHUB_TOKEN}
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
      - key: GITHUB_WEBHOOK_INVENTORY_BRANCHES
        value: "dev,staging,main"
      - key: GITHUB_CONNECT_TIMEOUT_MILLIS
        value: "10000"
      - key: GITHUB_READ_TIMEOUT_MILLIS
        value: "20000"
      - key: GITHUB_MAX_RETRIES
        value: "2"
      - key: GITHUB_RETRY_BACKOFF_MILLIS
        value: "500"
